#!/usr/bin/env python3
"""
build-md-store.py — Bundle ALL markdown content into a single JS object.

Why: Modern browsers (Chrome/Firefox/Safari) block fetch() over file:// scheme.
Opening reader.html directly from the filesystem therefore cannot load any .md
over HTTP. This script walks the workspace, reads every .md file, and emits
a single JS file assigning `window.DD_MD_STORE` so the reader can serve markdown
from memory without ever calling fetch().

Usage:
  python3 _assets/build-md-store.py

Output:
  _assets/md-store.js          (the bundled store + helpers)
  _assets/manifest-store.js    (inlined copy of .manifest.json)
  _assets/graph-store.js       (inlined copy of .graph.json)

Idempotent: safe to re-run anytime. No backups required.
"""
from __future__ import annotations

import datetime as _dt
import json
import os
import sys
from pathlib import Path

# --------------------------------------------------------------------------- #
ROOT = Path(__file__).resolve().parent.parent  # workspace root
ASSETS = ROOT / "_assets"

EXCLUDE_DIRS = {"_assets", "raw", "rendered", "node_modules", ".git"}
EXCLUDE_SUFFIXES = {".clean"}  # e.g. foo.md.clean


def should_skip(path: Path) -> bool:
    # Skip anything inside excluded directories (anywhere along the path).
    rel_parts = path.relative_to(ROOT).parts
    for part in rel_parts:
        if part in EXCLUDE_DIRS:
            return True
    # Skip .md.clean style backups.
    for suf in EXCLUDE_SUFFIXES:
        if path.name.endswith(suf):
            return True
    return False


def discover_markdown_files() -> list[Path]:
    out: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        # Prune excluded dirs in-place for speed.
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for fn in filenames:
            if not fn.lower().endswith(".md"):
                continue
            p = Path(dirpath) / fn
            if should_skip(p):
                continue
            out.append(p)
    out.sort()
    return out


def extract_title(body: str, fallback: str) -> str:
    """First H1 heading or file stem fallback."""
    for line in body.splitlines():
        line = line.strip()
        if line.startswith("# "):
            # Strip trailing anchor syntax like "# Heading {#id}".
            t = line[2:].strip()
            # Drop trailing {#...} if present.
            if t.endswith("}") and "{#" in t:
                t = t[: t.rfind("{#")].rstrip()
            return t
    return fallback


def build_md_store(files: list[Path]) -> dict:
    """Dict keyed by POSIX relative path (forward slashes)."""
    store: dict[str, dict] = {}
    total_bytes = 0
    for p in files:
        rel = p.relative_to(ROOT).as_posix()
        try:
            body = p.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            body = p.read_text(encoding="utf-8", errors="replace")
        st = p.stat()
        mtime_iso = _dt.datetime.fromtimestamp(
            st.st_mtime, tz=_dt.timezone.utc
        ).replace(microsecond=0).isoformat().replace("+00:00", "Z")
        title = extract_title(body, p.stem)
        store[rel] = {
            "title": title,
            "mtime": mtime_iso,
            "size": st.st_size,
            "content": body,
        }
        total_bytes += st.st_size
    return {"store": store, "total_bytes": total_bytes}


def write_md_store_js(store: dict, total_bytes: int, out_path: Path) -> int:
    generated_at = _dt.datetime.now(tz=_dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    meta = {
        "version": "1.0.0",
        "generatedAt": generated_at,
        "fileCount": len(store),
        "totalBytes": total_bytes,
    }
    # json.dumps handles all escaping (backticks, backslashes, newlines, unicode).
    store_json = json.dumps(store, ensure_ascii=False, separators=(",", ":"))
    meta_json = json.dumps(meta, ensure_ascii=False, separators=(",", ":"))

    js = f"""// Auto-generated by _assets/build-md-store.py — do NOT edit by hand.
// Bundled markdown content so reader.html works over file:// (where fetch() is blocked).
// Regenerate with: python3 _assets/build-md-store.py
(function () {{
  var STORE = {store_json};
  var META = {meta_json};

  // Normalize a path the way the reader passes it:
  //   - strip leading "./"
  //   - drop query + hash
  //   - collapse "../" / "./" segments (relative to workspace root)
  //   - preserve POSIX slashes
  function normalize(p) {{
    if (!p) return null;
    p = String(p);
    p = p.split('?')[0].split('#')[0];
    p = p.replace(/^\\.\\//, '').replace(/^\\/+/, '');
    var parts = p.split('/');
    var stack = [];
    for (var i = 0; i < parts.length; i++) {{
      var seg = parts[i];
      if (seg === '' || seg === '.') continue;
      if (seg === '..') {{ if (stack.length) stack.pop(); else return null; }}
      else stack.push(seg);
    }}
    return stack.join('/');
  }}

  window.DD_MD_STORE = STORE;
  window.DD_MD_STORE_META = META;
  window.DD_MD_STORE_GET = function (path) {{
    var n = normalize(path);
    if (!n) return null;
    if (STORE.hasOwnProperty(n)) return STORE[n];
    // Tolerate missing .md suffix.
    if (!/\\.md$/i.test(n) && STORE.hasOwnProperty(n + '.md')) return STORE[n + '.md'];
    return null;
  }};
  window.DD_MD_STORE_KEYS = function () {{ return Object.keys(STORE); }};
}})();
"""
    out_path.write_text(js, encoding="utf-8")
    return out_path.stat().st_size


def write_wrapped_json_js(src_json_path: Path, out_path: Path, global_var: str) -> int | None:
    if not src_json_path.exists():
        print(f"  [warn] source JSON missing: {src_json_path.name} (skipping {out_path.name})")
        return None
    try:
        data = json.loads(src_json_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"  [warn] cannot parse {src_json_path.name}: {e} (skipping {out_path.name})")
        return None
    generated_at = _dt.datetime.now(tz=_dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    js = f"""// Auto-generated by _assets/build-md-store.py at {generated_at}
// Inlined copy of {src_json_path.name} so pages work over file://.
(function () {{
  window.{global_var} = {payload};
}})();
"""
    out_path.write_text(js, encoding="utf-8")
    return out_path.stat().st_size


def fmt_bytes(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KB"
    return f"{n / (1024 * 1024):.2f} MB"


def main() -> int:
    if not ROOT.exists():
        print(f"ERROR: workspace root not found: {ROOT}", file=sys.stderr)
        return 2

    print(f"[build-md-store] workspace: {ROOT}")
    files = discover_markdown_files()
    print(f"[build-md-store] discovered {len(files)} markdown files")

    built = build_md_store(files)
    md_out = ASSETS / "md-store.js"
    md_size = write_md_store_js(built["store"], built["total_bytes"], md_out)
    print(f"[build-md-store] wrote {md_out.relative_to(ROOT)} -- "
          f"{len(built['store'])} files, {fmt_bytes(built['total_bytes'])} raw, "
          f"{fmt_bytes(md_size)} on disk")

    manifest_out = ASSETS / "manifest-store.js"
    m_size = write_wrapped_json_js(ROOT / ".manifest.json", manifest_out, "DD_MANIFEST")
    if m_size is not None:
        print(f"[build-md-store] wrote {manifest_out.relative_to(ROOT)} -- {fmt_bytes(m_size)}")

    graph_out = ASSETS / "graph-store.js"
    g_size = write_wrapped_json_js(ROOT / ".graph.json", graph_out, "DD_GRAPH")
    if g_size is not None:
        print(f"[build-md-store] wrote {graph_out.relative_to(ROOT)} -- {fmt_bytes(g_size)}")

    print("[build-md-store] done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
